### ISSUE TITLE
Install built APK to target

### ISSUE THREAD

**Issue by mattparks** [nisargjhaveri/vscode-android-debug#1]
Is it possible to add an APK install to selected target option along with the current "launch" and "attach" options?
It would be nice to integrate installing a modified APK before using the dual-debugger 😃.

**Comment by nisargjhaveri** [comment]
I'll look into ways to integrate installing an apk before launching. For now, it should be possible to install apk by creating a task that does `adb install` and specifying that task with [`preLaunchTask` in the launch configuration](https://code.visualstudio.com/docs/editor/debugging#_launchjson-attributes).

**Comment by nisargjhaveri** [comment]
I've just pushed a change that makes installing apk as part of the launch request possible. It should be included in the next release.
