### ISSUE TITLE
Kotlin support

### ISSUE THREAD

**Issue by sj6219** [nisargjhaveri/vscode-android-debug#2]
Do you have any plans to support Kotlin instead of Java?

**Comment by nisargjhaveri** [comment]
Unfortunately, not yet. We're currently using the [Language support for Java by Red Hat](https://marketplace.visualstudio.com/items?itemName=redhat.java) extension to provide java intellisense, which doesn't yet support Kotlin.

I'm exploring options to see if this can be enabled though. It'd be great to have Kotlin support as well.

**Comment by sj6219** [comment]
I think kotlin language can also be debugged at dual mode.
