### ISSUE TITLE
launch error at native mode

### ISSUE THREAD

**Issue by sj6219** [nisargjhaveri/vscode-android-debug#3]
When I run the launch in the "native" mode,  app is waiting for the debugger to attach  shown in the figure.
![image](https://user-images.githubusercontent.com/3592759/202847224-ecb8f921-6d84-4ebe-ac58-c38023bd9001.png)

**The debug console log is as follows.** 

Console is in 'commands' mode, prefix expressions with '?'.
Executing script: initCommands
  Platform: remote-android
 Connected: no

  Platform: remote-android
    Triple: aarch64-unknown-linux-android
OS Version: 33 (5.15.41-android13-8-00205-gf1bf82c3dacd-ab8747247)
  Hostname: localhost
 Connected: yes
WorkingDir: /data/user/0/com.carriez.flutter_hbb
    Kernel: #1 SMP PREEMPT Sun Jun 19 02:44:07 UTC 2022

Attached to process 9914

**The launch.json is as follows.** 
        {
            "name": "Android launch",
            "type": "android-debug",
            "request": "launch",
            "target": "select",
            //"target": "last-selected",
            "mode": "native", // Change to `java` or `native` to attach only Java or Native debugger.
            "packageName": "com.carriez.flutter_hbb", // Package name for your app.
            "launchActivity": ".MainActivity",  // Activity to launch
            "resumeProcess": true,
            "native": {
                "symbolSearchPaths": [
                    // "${workspaceFolder}/flutter/android/app/src/main/jniLibs/arm64-v8a/",
                ],
            },
            "java": {
                // "sourcePaths": ["${workspaceFolder}/flutter/android/app/src/main/java"]
            }

`

**Comment by nisargjhaveri** [comment]
In the debug console you should see two attached debuggers, one with name "Native" and another with the name given in the launch config ("Android launch" in your case). Can you please post the logs from the other one as well? It might help narrow down the issue. If you don't see anything interesting there, logs from "Android Debug" in the Output pane would also be useful.

Do you also have Android Studio open when this happens?

**Comment by sj6219** [comment]
yes. Android studio is open for android emulator.

**Android launch log**
Launching the app activity com.carriez.flutter_hbb/.MainActivity
Getting pid for the launched app
Attaching to process 12508 (com.carriez.flutter_hbb)
Starting Native debugger
Attached to process 12508
Resuming process by attaching Java debugger
Error resuming process: Could not successfully complete JDWP handshake

**Android Debug log**
[2022-11-20 9:46] [INFO] android resolveDebugConfiguration {
    "name": "Android launch",
    "type": "android-debug",
    "request": "launch",
    "target": "select",
    "mode": "native",
    "packageName": "com.carriez.flutter_hbb",
    "launchActivity": ".MainActivity",
    "resumeProcess": true,
    "native": {
        "symbolSearchPaths": []
    },
    "java": {},
    "__configurationTarget": 6
}
[2022-11-20 9:46] [INFO] Picked target {
    "udid": "emulator-5554",
    "state": "device",
    "product": "sdk_gphone64_arm64",
    "model": "sdk_gphone64_arm64",
    "device": "emu64a",
    "transport_id": "1",
    "type": "Emulator",
    "name": "Pixel 3a API 33-1",
    "avdName": "Pixel_3a_API_33-1"
}
[2022-11-20 9:46] [INFO] android resolveDebugConfigurationWithSubstitutedVariables {
    "name": "Android launch",
    "type": "android-debug",
    "request": "launch",
    "target": {
        "udid": "emulator-5554",
        "state": "device",
        "product": "sdk_gphone64_arm64",
        "model": "sdk_gphone64_arm64",
        "device": "emu64a",
        "transport_id": "1",
        "type": "Emulator",
        "name": "Pixel 3a API 33-1",
        "avdName": "Pixel_3a_API_33-1"
    },
    "mode": "native",
    "packageName": "com.carriez.flutter_hbb",
    "launchActivity": ".MainActivity",
    "resumeProcess": true,
    "native": {
        "symbolSearchPaths": [],
        "abiSupported": [
            "armeabi-v7a",
            "arm64-v8a",
            "x86",
            "x86_64"
        ],
        "abiMap": {}
    },
    "java": {},
    "__configurationTarget": 6
}
[2022-11-20 9:46] [INFO] android resolved debug configuration {
    "name": "Android launch",
    "type": "android-debug",
    "request": "launch",
    "target": {
        "udid": "emulator-5554",
        "state": "device",
        "product": "sdk_gphone64_arm64",
        "model": "sdk_gphone64_arm64",
        "device": "emu64a",
        "transport_id": "1",
        "type": "Emulator",
        "name": "Pixel 3a API 33-1",
        "avdName": "Pixel_3a_API_33-1"
    },
    "mode": "native",
    "packageName": "com.carriez.flutter_hbb",
    "launchActivity": ".MainActivity",
    "resumeProcess": true,
    "native": {
        "symbolSearchPaths": [],
        "abiSupported": [
            "armeabi-v7a",
            "arm64-v8a",
            "x86",
            "x86_64"
        ],
        "abiMap": {},
        "abi": "arm64-v8a"
    },
    "java": {},
    "__configurationTarget": 6
}
[2022-11-20 9:46] [INFO] getProcessList [
    {
        "pid": "574",
        "name": "system_server",
        "packages": []
    },
    {
        "pid": "763",
        "name": "com.android.systemui",
        "packages": []
    },
    {
        "pid": "845",
        "name": "com.android.bluetooth",
        "packages": []
    },
    {
        "pid": "862",
        "name": "com.android.networkstack.process",
        "packages": []
    },
    {
        "pid": "940",
        "name": "com.android.se",
        "packages": []
    },
    {
        "pid": "946",
        "name": "com.android.phone",
        "packages": []
    },
    {
        "pid": "965",
        "name": "com.google.android.ext.services",
        "packages": []
    },
    {
        "pid": "1140",
        "name": "com.google.android.gms.persistent",
        "packages": []
    },
    {
        "pid": "1191",
        "name": "com.google.android.apps.nexuslauncher",
        "packages": []
    },
    {
        "pid": "1468",
        "name": "com.google.android.inputmethod.latin",
        "packages": []
    },
    {
        "pid": "1506",
        "name": "com.google.android.providers.media.module",
        "packages": []
    },
    {
        "pid": "1523",
        "name": "com.google.android.googlequicksearchbox:interactor",
        "packages": []
    },
    {
        "pid": "1535",
        "name": "com.google.android.apps.messaging:rcs",
        "packages": []
    },
    {
        "pid": "1542",
        "name": "com.android.emulator.multidisplay",
        "packages": []
    },
    {
        "pid": "1723",
        "name": "com.google.android.googlequicksearchbox:search",
        "packages": []
    },
    {
        "pid": "9574",
        "name": "com.google.android.settings.intelligence",
        "packages": []
    },
    {
        "pid": "11637",
        "name": "com.android.providers.calendar",
        "packages": []
    },
    {
        "pid": "11786",
        "name": "com.android.settings",
        "packages": []
    },
    {
        "pid": "11816",
        "name": "com.google.android.gms",
        "packages": []
    },
    {
        "pid": "11908",
        "name": "com.google.android.webview:webview_service",
        "packages": []
    },
    {
        "pid": "11909",
        "name": "com.google.android.webview:sandboxed_process0:org.chromium.content.app.Sandbo",
        "packages": []
    },
    {
        "pid": "11958",
        "name": "com.google.android.googlequicksearchbox:privileged_process0",
        "packages": []
    },
    {
        "pid": "12311",
        "name": "com.google.android.apps.messaging",
        "packages": []
    },
    {
        "pid": "12339",
        "name": "com.google.process.gservices",
        "packages": []
    },
    {
        "pid": "12410",
        "name": "android.process.acore",
        "packages": []
    },
    {
        "pid": "12435",
        "name": "com.google.android.partnersetup",
        "packages": []
    },
    {
        "pid": "12508",
        "name": "com.carriez.flutter_hbb",
        "packages": []
    }
]
[2022-11-20 9:46] [INFO] lldb resolveDebugConfiguration {
    "type": "lldb",
    "name": "Native",
    "request": "attach",
    "pid": "12508",
    "androidTarget": "emulator-5554",
    "androidAbi": "arm64-v8a",
    "androidPackageName": "com.carriez.flutter_hbb",
    "symbolSearchPaths": [],
    "relativePathBase": "/Users/sjpark/rustdesk",
    "_adapterSettings": {
        "displayFormat": "auto",
        "showDisassembly": "auto",
        "dereferencePointers": true,
        "suppressMissingSourceFiles": true,
        "evaluationTimeout": 5,
        "consoleMode": "commands",
        "sourceLanguages": null,
        "terminalPromptClear": null,
        "evaluateForHovers": true,
        "commandCompletions": true,
        "reproducer": false
    }
}
[2022-11-20 9:46] [INFO] lldb resolveDebugConfigurationWithSubstitutedVariables {
    "type": "lldb",
    "name": "Native",
    "request": "attach",
    "pid": "12508",
    "androidTarget": {
        "udid": "emulator-5554",
        "state": "device",
        "product": "sdk_gphone64_arm64",
        "model": "sdk_gphone64_arm64",
        "device": "emu64a",
        "transport_id": "1"
    },
    "androidAbi": "arm64-v8a",
    "androidPackageName": "com.carriez.flutter_hbb",
    "symbolSearchPaths": [],
    "relativePathBase": "/Users/sjpark/rustdesk",
    "_adapterSettings": {
        "displayFormat": "auto",
        "showDisassembly": "auto",
        "dereferencePointers": true,
        "suppressMissingSourceFiles": true,
        "evaluationTimeout": 5,
        "consoleMode": "commands",
        "sourceLanguages": null,
        "terminalPromptClear": null,
        "evaluateForHovers": true,
        "commandCompletions": true,
        "reproducer": false
    },
    "androidAbiSupported": [
        "armeabi-v7a",
        "arm64-v8a",
        "x86",
        "x86_64"
    ],
    "androidAbiMap": {}
}
[2022-11-20 9:46] [INFO] Using lldb-server at /Users/sjpark/Library/Android/sdk/ndk/22.0.7026061/toolchains/llvm/prebuilt/darwin-x86_64/lib64/clang/11.0.5/lib/linux/aarch64/lldb-server
[2022-11-20 9:46] [INFO] lldb resolved debug configuration {
    "type": "lldb",
    "name": "Native",
    "request": "attach",
    "pid": "12508",
    "androidTarget": {
        "udid": "emulator-5554",
        "state": "device",
        "product": "sdk_gphone64_arm64",
        "model": "sdk_gphone64_arm64",
        "device": "emu64a",
        "transport_id": "1"
    },
    "androidAbi": "arm64-v8a",
    "androidPackageName": "com.carriez.flutter_hbb",
    "symbolSearchPaths": [],
    "relativePathBase": "/Users/sjpark/rustdesk",
    "_adapterSettings": {
        "displayFormat": "auto",
        "showDisassembly": "auto",
        "dereferencePointers": true,
        "suppressMissingSourceFiles": true,
        "evaluationTimeout": 5,
        "consoleMode": "commands",
        "sourceLanguages": null,
        "terminalPromptClear": null,
        "evaluateForHovers": true,
        "commandCompletions": true,
        "reproducer": false
    },
    "androidAbiSupported": [
        "armeabi-v7a",
        "arm64-v8a",
        "x86",
        "x86_64"
    ],
    "androidAbiMap": {},
    "androidLldbServerSocket": "/com.carriez.flutter_hbb/platform-985d5c3d60efa1ab924a9f00828dc204.sock",
    "initCommands": [
        "platform select remote-android",
        "platform connect unix-abstract-connect://[emulator-5554]/com.carriez.flutter_hbb/platform-985d5c3d60efa1ab924a9f00828dc204.sock",
        "settings set plugin.jit-loader.gdb.enable off"
    ]
}
[2022-11-20 9:46] [INFO] Debug session started (type: lldb, id: c56e99b0-36ac-445f-8a81-0563b5c19ef6)
[2022-11-20 9:46] [INFO] Error in JDWP handshake: Error: Could not read data in specified time
[2022-11-20 9:46] [INFO] Debug session started (type: android-debug, id: db73deb8-4e0b-406d-a5c1-85a0024436a8)

**Comment by sj6219** [comment]
Log when running in dual mode
[2022-11-20 10:4] [INFO] android resolveDebugConfiguration {
    "name": "Android launch",
    "type": "android-debug",
    "request": "launch",
    "target": "select",
    "mode": "dual",
    "packageName": "com.carriez.flutter_hbb",
    "launchActivity": ".MainActivity",
    "resumeProcess": true,
    "native": {
        "symbolSearchPaths": []
    },
    "java": {},
    "__configurationTarget": 6
}
[2022-11-20 10:6] [INFO] Picked target {
    "udid": "emulator-5554",
    "state": "device",
    "product": "sdk_gphone64_arm64",
    "model": "sdk_gphone64_arm64",
    "device": "emu64a",
    "transport_id": "1",
    "type": "Emulator",
    "name": "Pixel 3a API 33-1",
    "avdName": "Pixel_3a_API_33-1"
}
[2022-11-20 10:6] [INFO] android resolveDebugConfigurationWithSubstitutedVariables {
    "name": "Android launch",
    "type": "android-debug",
    "request": "launch",
    "target": {
        "udid": "emulator-5554",
        "state": "device",
        "product": "sdk_gphone64_arm64",
        "model": "sdk_gphone64_arm64",
        "device": "emu64a",
        "transport_id": "1",
        "type": "Emulator",
        "name": "Pixel 3a API 33-1",
        "avdName": "Pixel_3a_API_33-1"
    },
    "mode": "dual",
    "packageName": "com.carriez.flutter_hbb",
    "launchActivity": ".MainActivity",
    "resumeProcess": true,
    "native": {
        "symbolSearchPaths": [],
        "abiSupported": [
            "armeabi-v7a",
            "arm64-v8a",
            "x86",
            "x86_64"
        ],
        "abiMap": {}
    },
    "java": {},
    "__configurationTarget": 6
}
[2022-11-20 10:6] [INFO] android resolved debug configuration {
    "name": "Android launch",
    "type": "android-debug",
    "request": "launch",
    "target": {
        "udid": "emulator-5554",
        "state": "device",
        "product": "sdk_gphone64_arm64",
        "model": "sdk_gphone64_arm64",
        "device": "emu64a",
        "transport_id": "1",
        "type": "Emulator",
        "name": "Pixel 3a API 33-1",
        "avdName": "Pixel_3a_API_33-1"
    },
    "mode": "dual",
    "packageName": "com.carriez.flutter_hbb",
    "launchActivity": ".MainActivity",
    "resumeProcess": false,
    "native": {
        "symbolSearchPaths": [],
        "abiSupported": [
            "armeabi-v7a",
            "arm64-v8a",
            "x86",
            "x86_64"
        ],
        "abiMap": {},
        "abi": "arm64-v8a"
    },
    "java": {},
    "__configurationTarget": 6
}
[2022-11-20 10:6] [INFO] getProcessList [
    {
        "pid": "574",
        "name": "system_server",
        "packages": []
    },
    {
        "pid": "763",
        "name": "com.android.systemui",
        "packages": []
    },
    {
        "pid": "845",
        "name": "com.android.bluetooth",
        "packages": []
    },
    {
        "pid": "862",
        "name": "com.android.networkstack.process",
        "packages": []
    },
    {
        "pid": "940",
        "name": "com.android.se",
        "packages": []
    },
    {
        "pid": "946",
        "name": "com.android.phone",
        "packages": []
    },
    {
        "pid": "965",
        "name": "com.google.android.ext.services",
        "packages": []
    },
    {
        "pid": "1140",
        "name": "com.google.android.gms.persistent",
        "packages": []
    },
    {
        "pid": "1191",
        "name": "com.google.android.apps.nexuslauncher",
        "packages": []
    },
    {
        "pid": "1468",
        "name": "com.google.android.inputmethod.latin",
        "packages": []
    },
    {
        "pid": "1506",
        "name": "com.google.android.providers.media.module",
        "packages": []
    },
    {
        "pid": "1523",
        "name": "com.google.android.googlequicksearchbox:interactor",
        "packages": []
    },
    {
        "pid": "1535",
        "name": "com.google.android.apps.messaging:rcs",
        "packages": []
    },
    {
        "pid": "1542",
        "name": "com.android.emulator.multidisplay",
        "packages": []
    },
    {
        "pid": "1723",
        "name": "com.google.android.googlequicksearchbox:search",
        "packages": []
    },
    {
        "pid": "9574",
        "name": "com.google.android.settings.intelligence",
        "packages": []
    },
    {
        "pid": "11786",
        "name": "com.android.settings",
        "packages": []
    },
    {
        "pid": "11816",
        "name": "com.google.android.gms",
        "packages": []
    },
    {
        "pid": "11908",
        "name": "com.google.android.webview:webview_service",
        "packages": []
    },
    {
        "pid": "11909",
        "name": "com.google.android.webview:sandboxed_process0:org.chromium.content.app.Sandbo",
        "packages": []
    },
    {
        "pid": "11958",
        "name": "com.google.android.googlequicksearchbox:privileged_process0",
        "packages": []
    },
    {
        "pid": "12311",
        "name": "com.google.android.apps.messaging",
        "packages": []
    },
    {
        "pid": "12339",
        "name": "com.google.process.gservices",
        "packages": []
    },
    {
        "pid": "12410",
        "name": "android.process.acore",
        "packages": []
    },
    {
        "pid": "12435",
        "name": "com.google.android.partnersetup",
        "packages": []
    },
    {
        "pid": "12655",
        "name": "com.google.android.gms.unstable",
        "packages": []
    },
    {
        "pid": "13379",
        "name": "com.carriez.flutter_hbb",
        "packages": []
    }
]
[2022-11-20 10:6] [INFO] lldb resolveDebugConfiguration {
    "type": "lldb",
    "name": "Native",
    "request": "attach",
    "pid": "13379",
    "androidTarget": "emulator-5554",
    "androidAbi": "arm64-v8a",
    "androidPackageName": "com.carriez.flutter_hbb",
    "symbolSearchPaths": [],
    "relativePathBase": "/Users/sjpark/rustdesk",
    "_adapterSettings": {
        "displayFormat": "auto",
        "showDisassembly": "auto",
        "dereferencePointers": true,
        "suppressMissingSourceFiles": true,
        "evaluationTimeout": 5,
        "consoleMode": "commands",
        "sourceLanguages": null,
        "terminalPromptClear": null,
        "evaluateForHovers": true,
        "commandCompletions": true,
        "reproducer": false
    }
}
[2022-11-20 10:6] [INFO] lldb resolveDebugConfigurationWithSubstitutedVariables {
    "type": "lldb",
    "name": "Native",
    "request": "attach",
    "pid": "13379",
    "androidTarget": {
        "udid": "emulator-5554",
        "state": "device",
        "product": "sdk_gphone64_arm64",
        "model": "sdk_gphone64_arm64",
        "device": "emu64a",
        "transport_id": "1"
    },
    "androidAbi": "arm64-v8a",
    "androidPackageName": "com.carriez.flutter_hbb",
    "symbolSearchPaths": [],
    "relativePathBase": "/Users/sjpark/rustdesk",
    "_adapterSettings": {
        "displayFormat": "auto",
        "showDisassembly": "auto",
        "dereferencePointers": true,
        "suppressMissingSourceFiles": true,
        "evaluationTimeout": 5,
        "consoleMode": "commands",
        "sourceLanguages": null,
        "terminalPromptClear": null,
        "evaluateForHovers": true,
        "commandCompletions": true,
        "reproducer": false
    },
    "androidAbiSupported": [
        "armeabi-v7a",
        "arm64-v8a",
        "x86",
        "x86_64"
    ],
    "androidAbiMap": {}
}
[2022-11-20 10:6] [INFO] Using lldb-server at /Users/sjpark/Library/Android/sdk/ndk/22.0.7026061/toolchains/llvm/prebuilt/darwin-x86_64/lib64/clang/11.0.5/lib/linux/aarch64/lldb-server
[2022-11-20 10:6] [INFO] lldb resolved debug configuration {
    "type": "lldb",
    "name": "Native",
    "request": "attach",
    "pid": "13379",
    "androidTarget": {
        "udid": "emulator-5554",
        "state": "device",
        "product": "sdk_gphone64_arm64",
        "model": "sdk_gphone64_arm64",
        "device": "emu64a",
        "transport_id": "1"
    },
    "androidAbi": "arm64-v8a",
    "androidPackageName": "com.carriez.flutter_hbb",
    "symbolSearchPaths": [],
    "relativePathBase": "/Users/sjpark/rustdesk",
    "_adapterSettings": {
        "displayFormat": "auto",
        "showDisassembly": "auto",
        "dereferencePointers": true,
        "suppressMissingSourceFiles": true,
        "evaluationTimeout": 5,
        "consoleMode": "commands",
        "sourceLanguages": null,
        "terminalPromptClear": null,
        "evaluateForHovers": true,
        "commandCompletions": true,
        "reproducer": false
    },
    "androidAbiSupported": [
        "armeabi-v7a",
        "arm64-v8a",
        "x86",
        "x86_64"
    ],
    "androidAbiMap": {},
    "androidLldbServerSocket": "/com.carriez.flutter_hbb/platform-878ddd8dd0db747ff93468b9fb726e13.sock",
    "initCommands": [
        "platform select remote-android",
        "platform connect unix-abstract-connect://[emulator-5554]/com.carriez.flutter_hbb/platform-878ddd8dd0db747ff93468b9fb726e13.sock",
        "settings set plugin.jit-loader.gdb.enable off"
    ]
}
[2022-11-20 10:6] [INFO] Debug session started (type: lldb, id: 193bd132-10f3-4bb5-bcb9-fed47c2b8372)
[2022-11-20 10:6] [INFO] java resolveDebugConfiguration {
    "type": "java",
    "name": "Java",
    "request": "attach",
    "processId": "13379",
    "androidTarget": "emulator-5554"
}
[2022-11-20 10:6] [INFO] java resolveDebugConfigurationWithSubstitutedVariables {
    "type": "java",
    "name": "Java",
    "request": "attach",
    "androidTarget": {
        "udid": "emulator-5554",
        "state": "device",
        "product": "sdk_gphone64_arm64",
        "model": "sdk_gphone64_arm64",
        "device": "emu64a",
        "transport_id": "1"
    },
    "hostName": "localhost",
    "port": 8000,
    "androidPid": "13379"
}
[2022-11-20 10:6] [INFO] java resolved debug configuration {
    "type": "java",
    "name": "Java",
    "request": "attach",
    "androidTarget": {
        "udid": "emulator-5554",
        "state": "device",
        "product": "sdk_gphone64_arm64",
        "model": "sdk_gphone64_arm64",
        "device": "emu64a",
        "transport_id": "1"
    },
    "hostName": "localhost",
    "port": "56801",
    "androidPid": "13379",
    "androidJdwpPort": "56801"
}
[2022-11-20 10:6] [INFO] Debug session terminated (type: lldb, id: 193bd132-10f3-4bb5-bcb9-fed47c2b8372)
[2022-11-20 10:6] [INFO] Cleaning up lldb server at socket /com.carriez.flutter_hbb/platform-878ddd8dd0db747ff93468b9fb726e13.sock
[2022-11-20 10:8] [INFO] android resolveDebugConfiguration {
    "name": "Android launch",
    "type": "android-debug",
    "request": "launch",
    "target": "select",
    "mode": "dual",
    "packageName": "com.carriez.flutter_hbb",
    "launchActivity": ".MainActivity",
    "resumeProcess": true,
    "native": {
        "symbolSearchPaths": []
    },
    "java": {},
    "__configurationTarget": 6
}
[2022-11-20 10:8] [INFO] Picked target {
    "udid": "emulator-5554",
    "state": "device",
    "product": "sdk_gphone64_arm64",
    "model": "sdk_gphone64_arm64",
    "device": "emu64a",
    "transport_id": "1",
    "type": "Emulator",
    "name": "Pixel 3a API 33-1",
    "avdName": "Pixel_3a_API_33-1"
}
[2022-11-20 10:8] [INFO] android resolveDebugConfigurationWithSubstitutedVariables {
    "name": "Android launch",
    "type": "android-debug",
    "request": "launch",
    "target": {
        "udid": "emulator-5554",
        "state": "device",
        "product": "sdk_gphone64_arm64",
        "model": "sdk_gphone64_arm64",
        "device": "emu64a",
        "transport_id": "1",
        "type": "Emulator",
        "name": "Pixel 3a API 33-1",
        "avdName": "Pixel_3a_API_33-1"
    },
    "mode": "dual",
    "packageName": "com.carriez.flutter_hbb",
    "launchActivity": ".MainActivity",
    "resumeProcess": true,
    "native": {
        "symbolSearchPaths": [],
        "abiSupported": [
            "armeabi-v7a",
            "arm64-v8a",
            "x86",
            "x86_64"
        ],
        "abiMap": {}
    },
    "java": {},
    "__configurationTarget": 6
}
[2022-11-20 10:8] [INFO] android resolved debug configuration {
    "name": "Android launch",
    "type": "android-debug",
    "request": "launch",
    "target": {
        "udid": "emulator-5554",
        "state": "device",
        "product": "sdk_gphone64_arm64",
        "model": "sdk_gphone64_arm64",
        "device": "emu64a",
        "transport_id": "1",
        "type": "Emulator",
        "name": "Pixel 3a API 33-1",
        "avdName": "Pixel_3a_API_33-1"
    },
    "mode": "dual",
    "packageName": "com.carriez.flutter_hbb",
    "launchActivity": ".MainActivity",
    "resumeProcess": false,
    "native": {
        "symbolSearchPaths": [],
        "abiSupported": [
            "armeabi-v7a",
            "arm64-v8a",
            "x86",
            "x86_64"
        ],
        "abiMap": {},
        "abi": "arm64-v8a"
    },
    "java": {},
    "__configurationTarget": 6
}
[2022-11-20 10:8] [INFO] getProcessList [
    {
        "pid": "574",
        "name": "system_server",
        "packages": []
    },
    {
        "pid": "763",
        "name": "com.android.systemui",
        "packages": []
    },
    {
        "pid": "845",
        "name": "com.android.bluetooth",
        "packages": []
    },
    {
        "pid": "862",
        "name": "com.android.networkstack.process",
        "packages": []
    },
    {
        "pid": "940",
        "name": "com.android.se",
        "packages": []
    },
    {
        "pid": "946",
        "name": "com.android.phone",
        "packages": []
    },
    {
        "pid": "965",
        "name": "com.google.android.ext.services",
        "packages": []
    },
    {
        "pid": "1140",
        "name": "com.google.android.gms.persistent",
        "packages": []
    },
    {
        "pid": "1191",
        "name": "com.google.android.apps.nexuslauncher",
        "packages": []
    },
    {
        "pid": "1468",
        "name": "com.google.android.inputmethod.latin",
        "packages": []
    },
    {
        "pid": "1506",
        "name": "com.google.android.providers.media.module",
        "packages": []
    },
    {
        "pid": "1523",
        "name": "com.google.android.googlequicksearchbox:interactor",
        "packages": []
    },
    {
        "pid": "1535",
        "name": "com.google.android.apps.messaging:rcs",
        "packages": []
    },
    {
        "pid": "1542",
        "name": "com.android.emulator.multidisplay",
        "packages": []
    },
    {
        "pid": "1723",
        "name": "com.google.android.googlequicksearchbox:search",
        "packages": []
    },
    {
        "pid": "9574",
        "name": "com.google.android.settings.intelligence",
        "packages": []
    },
    {
        "pid": "11786",
        "name": "com.android.settings",
        "packages": []
    },
    {
        "pid": "11816",
        "name": "com.google.android.gms",
        "packages": []
    },
    {
        "pid": "11908",
        "name": "com.google.android.webview:webview_service",
        "packages": []
    },
    {
        "pid": "11909",
        "name": "com.google.android.webview:sandboxed_process0:org.chromium.content.app.Sandbo",
        "packages": []
    },
    {
        "pid": "11958",
        "name": "com.google.android.googlequicksearchbox:privileged_process0",
        "packages": []
    },
    {
        "pid": "12311",
        "name": "com.google.android.apps.messaging",
        "packages": []
    },
    {
        "pid": "12339",
        "name": "com.google.process.gservices",
        "packages": []
    },
    {
        "pid": "12410",
        "name": "android.process.acore",
        "packages": []
    },
    {
        "pid": "12435",
        "name": "com.google.android.partnersetup",
        "packages": []
    },
    {
        "pid": "12655",
        "name": "com.google.android.gms.unstable",
        "packages": []
    },
    {
        "pid": "13542",
        "name": "com.carriez.flutter_hbb",
        "packages": []
    }
]
[2022-11-20 10:8] [INFO] lldb resolveDebugConfiguration {
    "type": "lldb",
    "name": "Native",
    "request": "attach",
    "pid": "13542",
    "androidTarget": "emulator-5554",
    "androidAbi": "arm64-v8a",
    "androidPackageName": "com.carriez.flutter_hbb",
    "symbolSearchPaths": [],
    "relativePathBase": "/Users/sjpark/rustdesk",
    "_adapterSettings": {
        "displayFormat": "auto",
        "showDisassembly": "auto",
        "dereferencePointers": true,
        "suppressMissingSourceFiles": true,
        "evaluationTimeout": 5,
        "consoleMode": "commands",
        "sourceLanguages": null,
        "terminalPromptClear": null,
        "evaluateForHovers": true,
        "commandCompletions": true,
        "reproducer": false
    }
}
[2022-11-20 10:8] [INFO] lldb resolveDebugConfigurationWithSubstitutedVariables {
    "type": "lldb",
    "name": "Native",
    "request": "attach",
    "pid": "13542",
    "androidTarget": {
        "udid": "emulator-5554",
        "state": "device",
        "product": "sdk_gphone64_arm64",
        "model": "sdk_gphone64_arm64",
        "device": "emu64a",
        "transport_id": "1"
    },
    "androidAbi": "arm64-v8a",
    "androidPackageName": "com.carriez.flutter_hbb",
    "symbolSearchPaths": [],
    "relativePathBase": "/Users/sjpark/rustdesk",
    "_adapterSettings": {
        "displayFormat": "auto",
        "showDisassembly": "auto",
        "dereferencePointers": true,
        "suppressMissingSourceFiles": true,
        "evaluationTimeout": 5,
        "consoleMode": "commands",
        "sourceLanguages": null,
        "terminalPromptClear": null,
        "evaluateForHovers": true,
        "commandCompletions": true,
        "reproducer": false
    },
    "androidAbiSupported": [
        "armeabi-v7a",
        "arm64-v8a",
        "x86",
        "x86_64"
    ],
    "androidAbiMap": {}
}
[2022-11-20 10:8] [INFO] Using lldb-server at /Users/sjpark/Library/Android/sdk/ndk/22.0.7026061/toolchains/llvm/prebuilt/darwin-x86_64/lib64/clang/11.0.5/lib/linux/aarch64/lldb-server
[2022-11-20 10:8] [INFO] lldb resolved debug configuration {
    "type": "lldb",
    "name": "Native",
    "request": "attach",
    "pid": "13542",
    "androidTarget": {
        "udid": "emulator-5554",
        "state": "device",
        "product": "sdk_gphone64_arm64",
        "model": "sdk_gphone64_arm64",
        "device": "emu64a",
        "transport_id": "1"
    },
    "androidAbi": "arm64-v8a",
    "androidPackageName": "com.carriez.flutter_hbb",
    "symbolSearchPaths": [],
    "relativePathBase": "/Users/sjpark/rustdesk",
    "_adapterSettings": {
        "displayFormat": "auto",
        "showDisassembly": "auto",
        "dereferencePointers": true,
        "suppressMissingSourceFiles": true,
        "evaluationTimeout": 5,
        "consoleMode": "commands",
        "sourceLanguages": null,
        "terminalPromptClear": null,
        "evaluateForHovers": true,
        "commandCompletions": true,
        "reproducer": false
    },
    "androidAbiSupported": [
        "armeabi-v7a",
        "arm64-v8a",
        "x86",
        "x86_64"
    ],
    "androidAbiMap": {},
    "androidLldbServerSocket": "/com.carriez.flutter_hbb/platform-e5e2bde337b27b7c68df2e06e08d0430.sock",
    "initCommands": [
        "platform select remote-android",
        "platform connect unix-abstract-connect://[emulator-5554]/com.carriez.flutter_hbb/platform-e5e2bde337b27b7c68df2e06e08d0430.sock",
        "settings set plugin.jit-loader.gdb.enable off"
    ]
}
[2022-11-20 10:8] [INFO] Debug session started (type: lldb, id: e166a1a4-2512-400f-a1bc-702d85d44dde)
[2022-11-20 10:8] [INFO] java resolveDebugConfiguration {
    "type": "java",
    "name": "Java",
    "request": "attach",
    "processId": "13542",
    "androidTarget": "emulator-5554"
}
[2022-11-20 10:8] [INFO] java resolveDebugConfigurationWithSubstitutedVariables {
    "type": "java",
    "name": "Java",
    "request": "attach",
    "androidTarget": {
        "udid": "emulator-5554",
        "state": "device",
        "product": "sdk_gphone64_arm64",
        "model": "sdk_gphone64_arm64",
        "device": "emu64a",
        "transport_id": "1"
    },
    "hostName": "localhost",
    "port": 8000,
    "androidPid": "13542"
}
[2022-11-20 10:8] [INFO] java resolved debug configuration {
    "type": "java",
    "name": "Java",
    "request": "attach",
    "androidTarget": {
        "udid": "emulator-5554",
        "state": "device",
        "product": "sdk_gphone64_arm64",
        "model": "sdk_gphone64_arm64",
        "device": "emu64a",
        "transport_id": "1"
    },
    "hostName": "localhost",
    "port": "57201",
    "androidPid": "13542",
    "androidJdwpPort": "57201"
}
[2022-11-20 10:9] [INFO] Debug session terminated (type: lldb, id: e166a1a4-2512-400f-a1bc-702d85d44dde)
[2022-11-20 10:9] [INFO] Cleaning up lldb server at socket /com.carriez.flutter_hbb/platform-e5e2bde337b27b7c68df2e06e08d0430.sock

**Comment by nisargjhaveri** [comment]
Android Studio needs to be closed to make resume process or java debugger to work via this extension. Android Studio makes exclusive connections to the jvm and other tools can't connect during that time. I'll work on getting the error message better in the console to add this info.

You should be able to start emulator via the select target dialog as well, in case that is the only case you need Android Studio for.

In case you're planning to use native debugger in VS Code and java/kotlin debugger in Android Studio, attaching the java/kotlin debugger from Android Studio when it is waiting for debugger will resume the process and start debugging.

Hope this helps?

**Comment by sj6219** [comment]
Because android emulators run inside android studio, so only real Android devices can be debugged.

Debugging on the actual phone, it works well.
I think kotlin language can also be debugged at dual mode.
thank you.

**Comment by nisargjhaveri** [comment]
> Because android emulators run inside android studio, so only real Android devices can be debugged.

Curious, were you not able to start the emulator from VS Code? Just start the debugging, and select whichever emulator you want when it prompts to select the target device. It should start the selected emulator without Android Studio open.

**Comment by sj6219** [comment]
Thank you so much. I can't believe I only know this good function today.
