### ISSUE TITLE
ubuntu:"Cannot determine sdk root"

### ISSUE THREAD

**Issue by moroal** [nisargjhaveri/vscode-android-debug#5]
I have set the environment variable, but I still report an error, please help me to see how to deal with it, thank you very much

.bashrc
export ANDROID_HOME=$HOME/Android/Sdk
export PATH=$PATH:$ANDROID_HOME/tools

**Comment by nisargjhaveri** [comment]
@moroal, Glad that you were able to solve the issue!

If it was an issue with the extension, it might help if you can share the issue and solution. If it was some issue with your setup, can we please close this issue?

**Comment by moroal** [comment]
Starting vscode from the shell works just fine
@nisargjhaveri
